//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_ImpuestoServicio
    {
        public int Contrato_ImpuestoServicioId { get; set; }
        public Nullable<int> CodImpuesto { get; set; }
        public Nullable<int> ContratosId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
    }
}
