//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Domicilios()
        {
            this.Propiedades = new HashSet<Propiedades>();
        }
    
        public int DomiciliosId { get; set; }
        public string Calle { get; set; }
        public string Ciudad { get; set; }
        public string CP { get; set; }
        public Nullable<int> Piso { get; set; }
        public string Dto { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Barrio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Propiedades> Propiedades { get; set; }
    }
}
