//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarantePropietario
    {
        public int GarantePropietarioId { get; set; }
        public Nullable<int> PersonasId { get; set; }
        public Nullable<int> DomiciliosId { get; set; }
        public Nullable<int> Matricula { get; set; }
    }
}
