//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos_Detalle
    {
        public int PagoId { get; set; }
        public int TipoId { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<System.DateTime> PeriodoPago { get; set; }
    
        public virtual TiposImpuestosServicios TiposImpuestosServicios { get; set; }
    }
}
