//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int PagosId { get; set; }
        public Nullable<int> InquilinoId { get; set; }
        public Nullable<int> PropiedadId { get; set; }
        public Nullable<int> ContratoId { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public string Observaciones { get; set; }
    }
}
