//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propiedades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Propiedades()
        {
            this.Contratos = new HashSet<Contratos>();
        }
    
        public int IdEstate { get; set; }
        public Nullable<int> IdAddress { get; set; }
        public Nullable<int> IdOwner { get; set; }
        public Nullable<int> Propiedad { get; set; }
        public string NomenclaturaCatastral { get; set; }
        public string NumeroCtaRenta { get; set; }
        public Nullable<int> IdAdmConsorcio { get; set; }
        public Nullable<int> UnidadFacturacion { get; set; }
        public Nullable<int> NroFactura { get; set; }
        public Nullable<int> NroContratoEpec { get; set; }
    
        public virtual Domicilios Domicilios { get; set; }
        public virtual Personas Personas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contratos> Contratos { get; set; }
    }
}
